name              'dpkg_autostart'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
description       'Control service actions initialized from dpkg'
license           'Apache-2.0'
source_url        'https://github.com/sous-chefs/dpkg_autostart'
issues_url        'https://github.com/sous-chefs/dpkg_autostart/issues'
version           '0.4.4'
chef_version      '>= 12.15'

supports 'ubuntu'
supports 'debian'
