name              'dpkg_autostart'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
description       'Provides the dpkg_autostart resource for suppressing service starts during dpkg operations.'
license           'Apache-2.0'
source_url        'https://github.com/sous-chefs/dpkg_autostart'
issues_url        'https://github.com/sous-chefs/dpkg_autostart/issues'
version           '1.0.0'
chef_version      '>= 15.3'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'
