name 'dpkg_autostart'
version '0.2.0'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
description 'Control service actions initialized from dpkg'
license 'Apache-2.0'
source_url        'https://github.com/sous-chefs/dpkg_autostart'
issues_url        'https://github.com/sous-chefs/dpkg_autostart/issues'
supports 'ubuntu'
supports 'debian'
